version: "3"
services:

  bot:
    build: .
    volumes:
      - .:/src
    env_file:
      - .env
    command: python app.py
    depends_on:
      - db

  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
