"""initial_migration

Revision ID: 5938bb669cc8
Revises: 
Create Date: 2022-05-07 23:00:24.601975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5938bb669cc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeslot')
    op.drop_table('customer')
    op.drop_table('master')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('master_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='timeslot_customer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], name='timeslot_master_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='timeslot_pkey'),
    sa.UniqueConstraint('date', 'time', 'customer_id', name='timeslot_date_time_customer_id_key'),
    sa.UniqueConstraint('date', 'time', 'master_id', name='timeslot_date_time_master_id_key')
    )
    op.create_table('master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('info', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='master_pkey'),
    sa.UniqueConstraint('chat_id', name='master_chat_id_key'),
    sa.UniqueConstraint('phone', name='master_phone_key')
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customer_pkey'),
    sa.UniqueConstraint('chat_id', name='customer_chat_id_key'),
    sa.UniqueConstraint('phone', name='customer_phone_key')
    )
    # ### end Alembic commands ###
