"""alter_table_timeslot

Revision ID: 9560cc314685
Revises: eae9b581c161
Create Date: 2022-05-23 13:27:14.070269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9560cc314685'
down_revision = 'eae9b581c161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeslot', 'datetime')
    # ### end Alembic commands ###
