"""alter_tables_master_customer

Revision ID: ca5732179f1b
Revises: d2aabea16b61
Create Date: 2022-05-12 17:40:14.991193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5732179f1b'
down_revision = 'd2aabea16b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('photo_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'photo_id')
    # ### end Alembic commands ###
