"""add_table_portfoliophoto

Revision ID: eae9b581c161
Revises: ca5732179f1b
Create Date: 2022-05-15 21:18:14.640335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae9b581c161'
down_revision = 'ca5732179f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfoliophoto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.String(length=200), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('timeslot_master_id_fkey', 'timeslot', type_='foreignkey')
    op.create_foreign_key(None, 'timeslot', 'master', ['master_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeslot', type_='foreignkey')
    op.create_foreign_key('timeslot_master_id_fkey', 'timeslot', 'master', ['master_id'], ['id'], ondelete='CASCADE')
    op.drop_table('portfoliophoto')
    # ### end Alembic commands ###
