from .kb_admin_confirmation import kb_inform_confirm, kb_delete_confirm
from .kb_admin_statictics import kb_statistics
from .kb_customer_time_slots import kb_time_slots
from .kb_master_portfolio import kb_portfolio_photo
